[package]
name = "xilem"
version = "0.1.0"
edition = "2021"

# This is just a bin for now but will be a lib + examples soon

[features]
default = ["x11"]

gtk = ["glazier/gtk"]
x11 = ["glazier/x11"]
wayland = ["glazier/wayland"]

[dependencies]
vello = { git = "https://github.com/linebender/vello", rev = "f36e455" }
wgpu = "0.14"
raw-window-handle = "0.5"
png = "0.16.2"
rand = "0.7.3"
roxmltree = "0.13"
swash = "0.1.4"
bytemuck = { version = "1.7.2", features = ["derive"] }
parley = { git = "https://github.com/dfrg/parley" }
tokio = { version = "1.21", features = ["full"] }
futures-task = "0.3"
bitflags = "1.3.2"
tracing = "0.1.37"
test-log = "0.2.11"
env_logger = "0.10.0"
accesskit = "0.8.1"
either = "1.8.0"

[dependencies.glazier]
git = "https://github.com/linebender/glazier"
rev = "bb48024"
default-features = false
features = ["accesskit"]

[patch."https://github.com/dfrg/fount"]
fount = { git = "https://github.com/jneem/fount", rev = "361c76f" }

[patch.crates-io]
# Required for metal support to work on wgpu
# TODO: remove when wgpu is upgraded to 0.15
naga = { git = "https://github.com/gfx-rs/naga", rev="ddcd5d3121150b2b1beee6e54e9125ff31aaa9a2" }
